### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by slgwrt** [unkaer/Actions-OpenWrt#1]
我按照你的编译方式，能成功编译，但刷入R4A发现所有网线口无法连上，无轮LAN或WAN获取上级路由的IP都不行。

但直接刷你的 https://github.com/unkaer/Actions-OpenWrt-Xiaomi-R4A/releases/tag/min 这个是成功的。同样按照min的config去编译的 没修改。

知道这个是啥原因么？

**Comment by unkaer** [comment]
可能是太久没更新，lead的源码变了，我这边的修改文件没有更新。这两天有空已经修复了，应该没有问题了。重新 fork 后再试试吧

**Comment by slgwrt** [comment]
重新fork了，也是一样，会不会原本lede的源码就变更了问题？只是这次lan口正常了，但wan一样获取不了上级路由DHCP下来的IP，无线网就可以。

**Comment by unkaer** [comment]
我的 PPOE 协议 拨号上我的正常  刷的你的昨晚编译出来的游戏加速固件
![image](https://user-images.githubusercontent.com/45261780/126577327-9435b654-a001-4a96-baa9-400256712fdb.png)
然后接 DHCP客户端 协议 连上级路由也正常
![image](https://user-images.githubusercontent.com/45261780/126577600-e35540ae-0793-4c54-9111-e7781bbeb214.png)
你看看是不是你的设置那里出问题了，还是路由器出问题了
