### ISSUE TITLE
无法使用空密码进入管理后台，是什么我做错了吗

### ISSUE THREAD

**Issue by sbmatch** [unkaer/Actions-OpenWrt#10]
我通过breed控制台重置过后再次刷入您编译好的openwrt luci固件，依然被要求输入 root 密码以通过权限认证

**Comment by unkaer** [comment]
没毛病，密码是 password  好像换密码的那个命令失效了，懒得改了

**Comment by sbmatch** [comment]
> 没毛病，密码是 password 好像换密码的那个命令失效了，懒得改了

非常感谢您的解答，但在您向我提供明文后台登陆密码之前，已经通过burp工具成功暴力破解出这个密码，这个过程非常快速，是的，它的默认值属于一个弱密码
