### ISSUE TITLE
重启后配置丢失

### ISSUE THREAD

**Issue by ply99413** [unkaer/Actions-OpenWrt#14]
手动重启和断电重启都会丢失配置，跟刷完第一次开机一样，是什么问题呢

**Comment by unkaer** [comment]
还能跑的动？几年了就没管过的项目。隐约记得刷机包在设置那里有两个版本，好像一个是一个能存设置，一个不行。百度一下吧。这个路由器很久就没有玩了，我也不知道现在是啥情况

**Comment by ply99413** [comment]
解决了，是我大意了刷完kernal没刷sysupgrade的包，刷了sysupgrade就正常了，目前机器还能跑
