### ISSUE TITLE
我也想请教一个问题

### ISSUE THREAD

**Issue by Xiaodu233** [unkaer/Actions-OpenWrt#4]
进入SSH选择好插件后，按照您的教程按ctrl+D，无法直接退出SSH，应该要从底部的exit退出回到命令行，再按ctrl+D才能退出，但是编译好后，刷入发现插件没有对应我的选项，还是之前您的选项。所以我觉得是自己不会保存配置，希望能够在教程里写明（请原谅，第一次尝试没有经验）
注：第二次编译进入SSH，输入指令再进入菜单后选好并退出菜单，再次输入指令重进菜单，配置就变回了之前的配置，那么要怎么在菜单里保存配置呢。另外菜单里有save选项，可以保存*.config，那么应该是要保存后再到命令行应用吗？（抱歉说了这么多）

**Comment by unkaer** [comment]
在编辑 插件的页面 有个 save 方向键选择进行保存，或者 两下 ESC 返回，退出编辑菜单页面时会有一个保存提示。教程等会有空就改
