### ISSUE TITLE
关于breed

### ISSUE THREAD

**Issue by Evan-tc** [unkaer/Actions-OpenWrt#7]
你好。 我的是小米路由4A 千兆， 刷的breed-mt7621-pbr-m.bin ; 关于breed需要怎么设置呢，我breed没有设置，从breed刷了好几次其他的openwrt,都失败了。

**Comment by unkaer** [comment]
其他的openwrt,都失败了？也就是说我的这个版本能刷上吧？
关于breed我也不太懂，全是按着恩山论坛里的帖子来搞得的。
   我的理解：lede的源码好像不能直接用breed刷，要改源码成breed直刷的才行。原版怎么刷我不知道，所以就按照论坛里的方法来搞。其他的openwrt该怎么刷你要去问问提供openwrt的人。

**Comment by Evan-tc** [comment]
现在还没开始刷，所以想问问刷了breed后，breed要不要具体做什么设置，还是不用设置就直接刷你这和openwrt就可以啦 ，感谢回复。

**Comment by Evan-tc** [comment]
今天我从breed刷了openwrt了，可以刷。但是我重启路由或者断电openwrt就会丢失个人的所有的配置，就像新刷openwrt的状态一样。

**Comment by unkaer** [comment]
> 今天我从breed刷了openwrt了，可以刷。但是我重启路由或者断电openwrt就会丢失个人的所有的配置，就像新刷openwrt的状态一样。

编译完有两个固件
-initramfs-kernel    这个不能保存配置，重启后丢失
-squashfs-sysupgrade.bin   这个才是，正常用的
当你看见编译好有两个固件的时候，百度一下就不会出现这个问题了。刚好有空看见了就回复一下吧，估计你已经解决了

**Comment by unkaer** [comment]
> 



> 现在还没开始刷，所以想问问刷了breed后，breed要不要具体做什么设置，还是不用设置就直接刷你这和openwrt就可以啦 ，感谢回复。

没有什么需要特殊设置，只有一个小问题，直接刷 wifi效果 特别差，需要刷一下备份Eeprom.bin，这个文件统一一个型号的机器应该是一样的，恩山论坛上有人分享过。
