### ISSUE TITLE
无法安装ipk

### ISSUE THREAD

**Issue by zongou** [unkaer/Actions-OpenWrt#8]
breed刷入，无法安装ipk

**Comment by unkaer** [comment]
无法装哪个插件的 ipk，把你操作说清楚。
1. 是无法没有上传ipk安装的插件
2. 还是 手动上传的什么ipk，安装失败（架构错了，还是内存不足，还是缺少依赖，。。）
有问题问，麻烦以后写清楚点  看看[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**Comment by zongou** [comment]
今天重新刷试了一下，会报空间不足的错误，之前是报segment fault，no problem了
